trigger:
- main

pool:
  name: Default

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    cd Backend
    npm install
  displayName: Install Backend Dependencies

- script: |
    cd Frontend/resume-builder
    npm install
  displayName: Install Frontend Dependencies

- script: |
    cd Backend
    npm audit || exit 0
  displayName: Dependency Check

- script: |
    docker build -t backend ./Backend
  displayName: Build Backend Docker Image

